# Variables imported from this file can be accessed in any other file that calls it, specifically helpful for the game loop.
running = True # When this becomes false, the game will close
gamestage = "menu" # The stage that the game is in
buttonArray = []
levelbuttonArray = []
settingsbuttons = []
backgroundpicture = None # All of the variables declared to be None are just placeholders to be set in another file.
screen = None
level = None
levelobstacles = None
playerspaceship = None
allobjects = None
debug = True # Gives helpful features like fps counter, useful for debugging, not for the end-user to see.
allnonplayers = False
lang = None
languagesdict = None
instructionsbackbutton = None
wincondition = None
spawnPoint = None
spawnPointLocation = None
unlockedlevel = 1
leveltimer = None # The clock object that times each level.
leveltime = 0 # The number of milliseconds elapsed since the start of the level. Reset if the player respawns.
coins = 0
leveloverbackbutton = None
coinsgained = 0
bullets = None