# Variables imported from this file can be accessed in any other file that calls it, specifically helpful for the game loop
running = True # When this becomes false, the game will close
gamestage = "menu" # The stage that the game is in
buttonArray = []
levelbuttonArray = []
settingsbuttons = []
backgroundpicture = None # All of the variables declared to be None are just placeholders to be set in another file.
screen = None
level = None
levelobstacles = None
playerspaceship = None
allobjects = None
debug = False # Gives features like fps counter, 
allnonplayers = False
playerorigin = None
lang = None
languagesdict = None
instructionsbackbutton = None
wincondition = None